# Generated by Django 4.0.6 on 2022-10-17 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(auto_created='<django.db.models.fields.TextField>_<django.db.models.fields.TextField>@gmail.com', max_length=254)),
                ('name', models.TextField(max_length=80)),
                ('surname', models.TextField(max_length=80)),
                ('id_doctor', models.IntegerField()),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Time of create')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Time of update')),
                ('time_of_analyse', models.DateTimeField(verbose_name='Time of analyse')),
                ('is_corona', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=80)),
                ('surname', models.TextField(max_length=80)),
            ],
        ),
    ]
