# Generated by Django 4.1.2 on 2022-10-31 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_clients_doctor_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
