# Generated by Django 4.1.2 on 2022-11-06 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_client_delete_clients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='doctor_id',
            new_name='doctor',
        ),
    ]
